// Code generated by "stringer -type=AccessLevel"; DO NOT EDIT.

package domain

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AccessLevelUser-0]
	_ = x[AccessLevelViewAllUsers-1]
	_ = x[AccessLevelViewInventory-2]
	_ = x[AccessLevelViewMatches-3]
	_ = x[AccessLevelAdmin-4]
	_ = x[AccessLevelCreateItem-5]
	_ = x[AccessLevelGiveItem-6]
	_ = x[AccessLevelRevokeItem-7]
	_ = x[AccessLevelUpdateItem-8]
	_ = x[AccessLevelResetHwid-9]
	_ = x[AccessLevelAddAdmin-10]
	_ = x[AccessLevelDeleteItem-11]
	_ = x[AccessLevelDev-12]
}

const _AccessLevel_name = "AccessLevelUserAccessLevelViewAllUsersAccessLevelViewInventoryAccessLevelViewMatchesAccessLevelAdminAccessLevelCreateItemAccessLevelGiveItemAccessLevelRevokeItemAccessLevelUpdateItemAccessLevelResetHwidAccessLevelAddAdminAccessLevelDeleteItemAccessLevelDev"

var _AccessLevel_index = [...]uint16{0, 15, 38, 62, 84, 100, 121, 140, 161, 182, 202, 221, 242, 256}

func (i AccessLevel) String() string {
	if i < 0 || i >= AccessLevel(len(_AccessLevel_index)-1) {
		return "AccessLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AccessLevel_name[_AccessLevel_index[i]:_AccessLevel_index[i+1]]
}
