// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/intezya/auth_service/internal/domain/access_level"
	"github.com/intezya/auth_service/internal/infrastructure/ent/account"
	"github.com/intezya/auth_service/internal/infrastructure/ent/predicate"
)

// AccountUpdate is the builder for updating Account entities.
type AccountUpdate struct {
	config
	hooks    []Hook
	mutation *AccountMutation
}

// Where appends a list predicates to the AccountUpdate builder.
func (au *AccountUpdate) Where(ps ...predicate.Account) *AccountUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetUsername sets the "username" field.
func (au *AccountUpdate) SetUsername(s string) *AccountUpdate {
	au.mutation.SetUsername(s)
	return au
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (au *AccountUpdate) SetNillableUsername(s *string) *AccountUpdate {
	if s != nil {
		au.SetUsername(*s)
	}
	return au
}

// SetPassword sets the "password" field.
func (au *AccountUpdate) SetPassword(s string) *AccountUpdate {
	au.mutation.SetPassword(s)
	return au
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (au *AccountUpdate) SetNillablePassword(s *string) *AccountUpdate {
	if s != nil {
		au.SetPassword(*s)
	}
	return au
}

// SetHardwareID sets the "hardware_id" field.
func (au *AccountUpdate) SetHardwareID(s string) *AccountUpdate {
	au.mutation.SetHardwareID(s)
	return au
}

// SetNillableHardwareID sets the "hardware_id" field if the given value is not nil.
func (au *AccountUpdate) SetNillableHardwareID(s *string) *AccountUpdate {
	if s != nil {
		au.SetHardwareID(*s)
	}
	return au
}

// ClearHardwareID clears the value of the "hardware_id" field.
func (au *AccountUpdate) ClearHardwareID() *AccountUpdate {
	au.mutation.ClearHardwareID()
	return au
}

// SetAccessLevel sets the "access_level" field.
func (au *AccountUpdate) SetAccessLevel(all access_level.AccessLevel) *AccountUpdate {
	au.mutation.SetAccessLevel(all)
	return au
}

// SetNillableAccessLevel sets the "access_level" field if the given value is not nil.
func (au *AccountUpdate) SetNillableAccessLevel(all *access_level.AccessLevel) *AccountUpdate {
	if all != nil {
		au.SetAccessLevel(*all)
	}
	return au
}

// SetBannedUntil sets the "banned_until" field.
func (au *AccountUpdate) SetBannedUntil(t time.Time) *AccountUpdate {
	au.mutation.SetBannedUntil(t)
	return au
}

// SetNillableBannedUntil sets the "banned_until" field if the given value is not nil.
func (au *AccountUpdate) SetNillableBannedUntil(t *time.Time) *AccountUpdate {
	if t != nil {
		au.SetBannedUntil(*t)
	}
	return au
}

// ClearBannedUntil clears the value of the "banned_until" field.
func (au *AccountUpdate) ClearBannedUntil() *AccountUpdate {
	au.mutation.ClearBannedUntil()
	return au
}

// SetBanReason sets the "ban_reason" field.
func (au *AccountUpdate) SetBanReason(s string) *AccountUpdate {
	au.mutation.SetBanReason(s)
	return au
}

// SetNillableBanReason sets the "ban_reason" field if the given value is not nil.
func (au *AccountUpdate) SetNillableBanReason(s *string) *AccountUpdate {
	if s != nil {
		au.SetBanReason(*s)
	}
	return au
}

// ClearBanReason clears the value of the "ban_reason" field.
func (au *AccountUpdate) ClearBanReason() *AccountUpdate {
	au.mutation.ClearBanReason()
	return au
}

// Mutation returns the AccountMutation object of the builder.
func (au *AccountUpdate) Mutation() *AccountMutation {
	return au.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AccountUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AccountUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AccountUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AccountUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *AccountUpdate) check() error {
	if v, ok := au.mutation.Username(); ok {
		if err := account.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Account.username": %w`, err)}
		}
	}
	if v, ok := au.mutation.Password(); ok {
		if err := account.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "Account.password": %w`, err)}
		}
	}
	return nil
}

func (au *AccountUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := au.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.Username(); ok {
		_spec.SetField(account.FieldUsername, field.TypeString, value)
	}
	if value, ok := au.mutation.Password(); ok {
		_spec.SetField(account.FieldPassword, field.TypeString, value)
	}
	if value, ok := au.mutation.HardwareID(); ok {
		_spec.SetField(account.FieldHardwareID, field.TypeString, value)
	}
	if au.mutation.HardwareIDCleared() {
		_spec.ClearField(account.FieldHardwareID, field.TypeString)
	}
	if value, ok := au.mutation.AccessLevel(); ok {
		_spec.SetField(account.FieldAccessLevel, field.TypeString, value)
	}
	if value, ok := au.mutation.BannedUntil(); ok {
		_spec.SetField(account.FieldBannedUntil, field.TypeTime, value)
	}
	if au.mutation.BannedUntilCleared() {
		_spec.ClearField(account.FieldBannedUntil, field.TypeTime)
	}
	if value, ok := au.mutation.BanReason(); ok {
		_spec.SetField(account.FieldBanReason, field.TypeString, value)
	}
	if au.mutation.BanReasonCleared() {
		_spec.ClearField(account.FieldBanReason, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AccountUpdateOne is the builder for updating a single Account entity.
type AccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountMutation
}

// SetUsername sets the "username" field.
func (auo *AccountUpdateOne) SetUsername(s string) *AccountUpdateOne {
	auo.mutation.SetUsername(s)
	return auo
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillableUsername(s *string) *AccountUpdateOne {
	if s != nil {
		auo.SetUsername(*s)
	}
	return auo
}

// SetPassword sets the "password" field.
func (auo *AccountUpdateOne) SetPassword(s string) *AccountUpdateOne {
	auo.mutation.SetPassword(s)
	return auo
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillablePassword(s *string) *AccountUpdateOne {
	if s != nil {
		auo.SetPassword(*s)
	}
	return auo
}

// SetHardwareID sets the "hardware_id" field.
func (auo *AccountUpdateOne) SetHardwareID(s string) *AccountUpdateOne {
	auo.mutation.SetHardwareID(s)
	return auo
}

// SetNillableHardwareID sets the "hardware_id" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillableHardwareID(s *string) *AccountUpdateOne {
	if s != nil {
		auo.SetHardwareID(*s)
	}
	return auo
}

// ClearHardwareID clears the value of the "hardware_id" field.
func (auo *AccountUpdateOne) ClearHardwareID() *AccountUpdateOne {
	auo.mutation.ClearHardwareID()
	return auo
}

// SetAccessLevel sets the "access_level" field.
func (auo *AccountUpdateOne) SetAccessLevel(all access_level.AccessLevel) *AccountUpdateOne {
	auo.mutation.SetAccessLevel(all)
	return auo
}

// SetNillableAccessLevel sets the "access_level" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillableAccessLevel(all *access_level.AccessLevel) *AccountUpdateOne {
	if all != nil {
		auo.SetAccessLevel(*all)
	}
	return auo
}

// SetBannedUntil sets the "banned_until" field.
func (auo *AccountUpdateOne) SetBannedUntil(t time.Time) *AccountUpdateOne {
	auo.mutation.SetBannedUntil(t)
	return auo
}

// SetNillableBannedUntil sets the "banned_until" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillableBannedUntil(t *time.Time) *AccountUpdateOne {
	if t != nil {
		auo.SetBannedUntil(*t)
	}
	return auo
}

// ClearBannedUntil clears the value of the "banned_until" field.
func (auo *AccountUpdateOne) ClearBannedUntil() *AccountUpdateOne {
	auo.mutation.ClearBannedUntil()
	return auo
}

// SetBanReason sets the "ban_reason" field.
func (auo *AccountUpdateOne) SetBanReason(s string) *AccountUpdateOne {
	auo.mutation.SetBanReason(s)
	return auo
}

// SetNillableBanReason sets the "ban_reason" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillableBanReason(s *string) *AccountUpdateOne {
	if s != nil {
		auo.SetBanReason(*s)
	}
	return auo
}

// ClearBanReason clears the value of the "ban_reason" field.
func (auo *AccountUpdateOne) ClearBanReason() *AccountUpdateOne {
	auo.mutation.ClearBanReason()
	return auo
}

// Mutation returns the AccountMutation object of the builder.
func (auo *AccountUpdateOne) Mutation() *AccountMutation {
	return auo.mutation
}

// Where appends a list predicates to the AccountUpdate builder.
func (auo *AccountUpdateOne) Where(ps ...predicate.Account) *AccountUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AccountUpdateOne) Select(field string, fields ...string) *AccountUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Account entity.
func (auo *AccountUpdateOne) Save(ctx context.Context) (*Account, error) {
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AccountUpdateOne) SaveX(ctx context.Context) *Account {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AccountUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AccountUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *AccountUpdateOne) check() error {
	if v, ok := auo.mutation.Username(); ok {
		if err := account.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Account.username": %w`, err)}
		}
	}
	if v, ok := auo.mutation.Password(); ok {
		if err := account.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "Account.password": %w`, err)}
		}
	}
	return nil
}

func (auo *AccountUpdateOne) sqlSave(ctx context.Context) (_node *Account, err error) {
	if err := auo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Account.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, account.FieldID)
		for _, f := range fields {
			if !account.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != account.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.Username(); ok {
		_spec.SetField(account.FieldUsername, field.TypeString, value)
	}
	if value, ok := auo.mutation.Password(); ok {
		_spec.SetField(account.FieldPassword, field.TypeString, value)
	}
	if value, ok := auo.mutation.HardwareID(); ok {
		_spec.SetField(account.FieldHardwareID, field.TypeString, value)
	}
	if auo.mutation.HardwareIDCleared() {
		_spec.ClearField(account.FieldHardwareID, field.TypeString)
	}
	if value, ok := auo.mutation.AccessLevel(); ok {
		_spec.SetField(account.FieldAccessLevel, field.TypeString, value)
	}
	if value, ok := auo.mutation.BannedUntil(); ok {
		_spec.SetField(account.FieldBannedUntil, field.TypeTime, value)
	}
	if auo.mutation.BannedUntilCleared() {
		_spec.ClearField(account.FieldBannedUntil, field.TypeTime)
	}
	if value, ok := auo.mutation.BanReason(); ok {
		_spec.SetField(account.FieldBanReason, field.TypeString, value)
	}
	if auo.mutation.BanReasonCleared() {
		_spec.ClearField(account.FieldBanReason, field.TypeString)
	}
	_node = &Account{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
