// Code generated by "stringer -type=AccessLevel"; DO NOT EDIT.

package access_level

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[User-0]
	_ = x[ViewAllUsers-1]
	_ = x[ViewInventory-2]
	_ = x[ViewMatches-3]
	_ = x[Admin-4]
	_ = x[CreateItem-5]
	_ = x[GiveItem-6]
	_ = x[RevokeItem-7]
	_ = x[UpdateItem-8]
	_ = x[ResetHwid-9]
	_ = x[AddAdmin-10]
	_ = x[DeleteItem-11]
	_ = x[Dev-12]
}

const _AccessLevel_name = "UserViewAllUsersViewInventoryViewMatchesAdminCreateItemGiveItemRevokeItemUpdateItemResetHwidAddAdminDeleteItemDev"

var _AccessLevel_index = [...]uint8{0, 4, 16, 29, 40, 45, 55, 63, 73, 83, 92, 100, 110, 113}

func (i AccessLevel) String() string {
	if i < 0 || i >= AccessLevel(len(_AccessLevel_index)-1) {
		return "AccessLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AccessLevel_name[_AccessLevel_index[i]:_AccessLevel_index[i+1]]
}
