// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: auth/auth.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{0}
}

type AuthenticationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	HardwareId    string                 `protobuf:"bytes,3,opt,name=hardware_id,json=hardwareId,proto3" json:"hardware_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticationRequest) Reset() {
	*x = AuthenticationRequest{}
	mi := &file_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationRequest) ProtoMessage() {}

func (x *AuthenticationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationRequest.ProtoReflect.Descriptor instead.
func (*AuthenticationRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticationRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthenticationRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AuthenticationRequest) GetHardwareId() string {
	if x != nil {
		return x.HardwareId
	}
	return ""
}

type TokenResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Token             string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	AccessLevel       int64                  `protobuf:"varint,2,opt,name=access_level,json=accessLevel,proto3" json:"access_level,omitempty"`
	IsBanned          bool                   `protobuf:"varint,3,opt,name=is_banned,json=isBanned,proto3" json:"is_banned,omitempty"`
	BannedUntilInUnix int64                  `protobuf:"varint,4,opt,name=banned_until_in_unix,json=bannedUntilInUnix,proto3" json:"banned_until_in_unix,omitempty"` // 0 = inf
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{2}
}

func (x *TokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenResponse) GetAccessLevel() int64 {
	if x != nil {
		return x.AccessLevel
	}
	return 0
}

func (x *TokenResponse) GetIsBanned() bool {
	if x != nil {
		return x.IsBanned
	}
	return false
}

func (x *TokenResponse) GetBannedUntilInUnix() int64 {
	if x != nil {
		return x.BannedUntilInUnix
	}
	return 0
}

type VerifyTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenRequest) Reset() {
	*x = VerifyTokenRequest{}
	mi := &file_auth_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenRequest) ProtoMessage() {}

func (x *VerifyTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type VerifyTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       int64                  `protobuf:"varint,1,opt,name=subject,proto3" json:"subject,omitempty"`
	AccessLevel   int64                  `protobuf:"varint,2,opt,name=access_level,json=accessLevel,proto3" json:"access_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenResponse) Reset() {
	*x = VerifyTokenResponse{}
	mi := &file_auth_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenResponse) ProtoMessage() {}

func (x *VerifyTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenResponse.ProtoReflect.Descriptor instead.
func (*VerifyTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyTokenResponse) GetSubject() int64 {
	if x != nil {
		return x.Subject
	}
	return 0
}

func (x *VerifyTokenResponse) GetAccessLevel() int64 {
	if x != nil {
		return x.AccessLevel
	}
	return 0
}

type BanAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       int64                  `protobuf:"varint,1,opt,name=subject,proto3" json:"subject,omitempty"`
	BanUntilUnix  int64                  `protobuf:"varint,2,opt,name=ban_until_unix,json=banUntilUnix,proto3" json:"ban_until_unix,omitempty"` // 0 = inf
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanAccountRequest) Reset() {
	*x = BanAccountRequest{}
	mi := &file_auth_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanAccountRequest) ProtoMessage() {}

func (x *BanAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanAccountRequest.ProtoReflect.Descriptor instead.
func (*BanAccountRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{5}
}

func (x *BanAccountRequest) GetSubject() int64 {
	if x != nil {
		return x.Subject
	}
	return 0
}

func (x *BanAccountRequest) GetBanUntilUnix() int64 {
	if x != nil {
		return x.BanUntilUnix
	}
	return 0
}

func (x *BanAccountRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_auth_auth_proto protoreflect.FileDescriptor

const file_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x0fauth/auth.proto\x12\x04auth\"\a\n" +
	"\x05Empty\"p\n" +
	"\x15AuthenticationRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1f\n" +
	"\vhardware_id\x18\x03 \x01(\tR\n" +
	"hardwareId\"\x96\x01\n" +
	"\rTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12!\n" +
	"\faccess_level\x18\x02 \x01(\x03R\vaccessLevel\x12\x1b\n" +
	"\tis_banned\x18\x03 \x01(\bR\bisBanned\x12/\n" +
	"\x14banned_until_in_unix\x18\x04 \x01(\x03R\x11bannedUntilInUnix\"*\n" +
	"\x12VerifyTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"R\n" +
	"\x13VerifyTokenResponse\x12\x18\n" +
	"\asubject\x18\x01 \x01(\x03R\asubject\x12!\n" +
	"\faccess_level\x18\x02 \x01(\x03R\vaccessLevel\"k\n" +
	"\x11BanAccountRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\x03R\asubject\x12$\n" +
	"\x0eban_until_unix\x18\x02 \x01(\x03R\fbanUntilUnix\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason2\xf6\x01\n" +
	"\vAuthService\x124\n" +
	"\bRegister\x12\x1b.auth.AuthenticationRequest\x1a\v.auth.Empty\x129\n" +
	"\x05Login\x12\x1b.auth.AuthenticationRequest\x1a\x13.auth.TokenResponse\x12B\n" +
	"\vVerifyToken\x12\x18.auth.VerifyTokenRequest\x1a\x19.auth.VerifyTokenResponse\x122\n" +
	"\n" +
	"BanAccount\x12\x17.auth.BanAccountRequest\x1a\v.auth.EmptyB7Z5github.com/intezya/auth-service/protos/go/auth;authpbb\x06proto3"

var (
	file_auth_auth_proto_rawDescOnce sync.Once
	file_auth_auth_proto_rawDescData []byte
)

func file_auth_auth_proto_rawDescGZIP() []byte {
	file_auth_auth_proto_rawDescOnce.Do(func() {
		file_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_auth_proto_rawDesc), len(file_auth_auth_proto_rawDesc)))
	})
	return file_auth_auth_proto_rawDescData
}

var file_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_auth_auth_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: auth.Empty
	(*AuthenticationRequest)(nil), // 1: auth.AuthenticationRequest
	(*TokenResponse)(nil),         // 2: auth.TokenResponse
	(*VerifyTokenRequest)(nil),    // 3: auth.VerifyTokenRequest
	(*VerifyTokenResponse)(nil),   // 4: auth.VerifyTokenResponse
	(*BanAccountRequest)(nil),     // 5: auth.BanAccountRequest
}
var file_auth_auth_proto_depIdxs = []int32{
	1, // 0: auth.AuthService.Register:input_type -> auth.AuthenticationRequest
	1, // 1: auth.AuthService.Login:input_type -> auth.AuthenticationRequest
	3, // 2: auth.AuthService.VerifyToken:input_type -> auth.VerifyTokenRequest
	5, // 3: auth.AuthService.BanAccount:input_type -> auth.BanAccountRequest
	0, // 4: auth.AuthService.Register:output_type -> auth.Empty
	2, // 5: auth.AuthService.Login:output_type -> auth.TokenResponse
	4, // 6: auth.AuthService.VerifyToken:output_type -> auth.VerifyTokenResponse
	0, // 7: auth.AuthService.BanAccount:output_type -> auth.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_auth_proto_init() }
func file_auth_auth_proto_init() {
	if File_auth_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_auth_proto_rawDesc), len(file_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_auth_proto_goTypes,
		DependencyIndexes: file_auth_auth_proto_depIdxs,
		MessageInfos:      file_auth_auth_proto_msgTypes,
	}.Build()
	File_auth_auth_proto = out.File
	file_auth_auth_proto_goTypes = nil
	file_auth_auth_proto_depIdxs = nil
}
